jobs:
- job: Build
  steps:
    - task: PowerShell@2
      displayName: "Install dependencies"
      inputs:
        targetType: 'inline'
        script: 'npm ci'
        workingDirectory: TestCases/

    - task: AzureCLI@2
      displayName: Run Playwright Test
      env:
        PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
        PLAYWRIGHT_SERVICE_RUN_ID: $(Build.DefinitionName) - $(Build.BuildNumber) - $(System.JobAttempt)
      inputs:
        azureSubscription: 'LoueyZormati'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          npx playwright test --config=playwright.service.config.js --workers=2
        addSpnToEnvironment: true

    # Vérifier si le dossier playwright-report existe
    - task: PowerShell@2
      displayName: "Check if Playwright report exists"
      inputs:
        targetType: 'inline'
        script: |
          if (Test-Path -Path "TestCases/playwright-report") {
            Write-Host "✅ Playwright report found."
          } else {
            Write-Host "❌ Playwright report not found!"
            exit 1
          }

    # Publier le rapport Playwright
    - task: PublishPipelineArtifact@1
      displayName: Upload Playwright report
      inputs:
        targetPath: 'TestCases/playwright-report/' # Chemin mis à jour
        artifact: 'playwright-report'
        publishLocation: 'pipeline'
