jobs:
  - job: Build
    steps:
      - script: echo "### Steps exécutées: $(System.JobName)"
        displayName: "Debug - Afficher les étapes du job"

      - script: ls -la
        displayName: "Debug - Vérifier le contenu du répertoire courant"

      - task: PowerShell@2
        displayName: "Install dependencies"
        inputs:
          targetType: 'inline'
          script: |
            npm ci
            npx playwright install --with-deps
            npx playwright --version
          workingDirectory: TestCases/

      - script: |
          echo "PLAYWRIGHT_SERVICE_URL: $PLAYWRIGHT_SERVICE_URL"
          echo "PLAYWRIGHT_SERVICE_RUN_ID: $BUILD_DEFINITIONNAME - $BUILD_BUILDNUMBER - $SYSTEM_JOBATTEMPT"
          npx playwright test --config=playwright.service.config.js --verbose
        displayName: "Run Playwright Test"
        env:
          PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
          PLAYWRIGHT_SERVICE_RUN_ID: $(Build.DefinitionName) - $(Build.BuildNumber) - $(System.JobAttempt)

      - task: PublishPipelineArtifact@1
        displayName: Upload Pla
