jobs:
  - job: Build
    steps:
      - task: PowerShell@2
        displayName: "Install dependencies"
        inputs:
          targetType: 'inline'
          script: 'npm ci'
          workingDirectory: TestCases/

      - task: PowerShell@2
        displayName: "Clean old report"
        inputs:
          targetType: 'inline'
          script: 'Remove-Item -Recurse -Force TestCases/playwright-report/*'

      - task: AzureCLI@2
        displayName: "Run Playwright Test on multiple browsers"
        env:
          PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
          PLAYWRIGHT_SERVICE_RUN_ID: $(Build.DefinitionName) - $(Build.BuildNumber) - $(System.JobAttempt)
        inputs:
          azureSubscription: 'LoueyZormati'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            npx playwright test --config=playwright.service.config.js --workers=2
          addSpnToEnvironment: true

      - task: PublishPipelineArtifact@1
        displayName: "Upload Playwright report"
        inputs:
          targetPath: TestCases/playwright-report/
          artifact: 'playwright-report'
          publishLocation: 'pipeline'